# Generated by Django 5.2.7 on 2025-11-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0002_alter_customuser_follower_alter_customuser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
