# Generated by Django 5.2.7 on 2026-01-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0002_massage'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
