# Generated by Django 5.2.7 on 2025-11-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
