# Generated by Django 5.2.7 on 2026-01-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0003_massage_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='sppk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
