# Generated by Django 5.2.7 on 2026-01-08 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0004_massage_sppk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='sppk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instagramapp.post'),
        ),
    ]
