# Generated by Django 5.2.7 on 2025-11-20 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0004_alter_coment_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.TextField()),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='by_people', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_people', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
