# Generated by Django 5.2.7 on 2025-12-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramapp', '0005_massage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
